version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - java -version
      - echo Build Starting on `date`
      - chmod +x ./gradlew
      - ./gradlew build
      
#artifacts:
#  files:
#    - '**/*'
#  base-directory: 'target/my-web-app'