version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Build Starting on `date`
      - chmod +x ./mzcctcsa/gradlew
      - ./mzcctcsa/gradlew build
      
artifacts:
  files:
    - /mzcctcsa/build/libs/mzcctcsa-0.0.1-SNAPSHOT.jar
#  base-directory: 'target/my-web-app'